# Generated by Django 5.1.3 on 2024-12-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCodeAndCountryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=255)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code_number', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccountinfo',
            name='user',
        ),
        migrations.CreateModel(
            name='CityAndCountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code_number', models.BigIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='new_app.countrycodeandcountryname', to_field='country_code_number')),
            ],
        ),
    ]
