# Generated by Django 5.1.3 on 2024-12-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_countrycodeandcountryname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityandcountrycode',
            name='country_code_number',
        ),
        migrations.AlterField(
            model_name='cityandcountrycode',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='new_app.countrycodeandcountryname', to_field='country_code_number'),
        ),
    ]
