# Generated by Django 5.1.3 on 2024-12-21 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_countrycodeandcountryname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountinfo',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
