# Generated by Django 5.1.3 on 2024-12-19 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_remove_cityandcountrycode_country_code_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityandcountrycode',
            name='country_code_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cityandcountrycode',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='new_app.countrycodeandcountryname', to_field='country_code_number'),
        ),
    ]
