# Generated by Django 5.1.3 on 2025-01-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_imagewithcoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewithcoordinates',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagewithcoordinates',
            name='level',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagewithcoordinates',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
