# Generated by Django 5.1.3 on 2025-01-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_imagewithcoordinates_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
