# Generated by Django 5.1.3 on 2024-12-19 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_remove_cityandcountrycode_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityandcountrycode',
            name='country_code_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='new_app.countrycodeandcountryname', to_field='country_code_number'),
            preserve_default=False,
        ),
    ]
