# Generated by Django 5.1.3 on 2025-01-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_achievement_useraccountinfo_countfindcats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='currentProgress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='maxProgress',
            field=models.IntegerField(default=5),
        ),
    ]
