# Generated by Django 5.1.3 on 2024-12-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_remove_cityandcountrycode_country_code_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrycodeandcountryname',
            name='country_code_number',
        ),
    ]
