# Generated by Django 5.1.3 on 2025-01-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0009_achievement_currentprogress_achievement_maxprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountinfo',
            name='kisKis',
            field=models.IntegerField(default=100),
        ),
    ]
