# Generated by Django 5.1.3 on 2025-02-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0010_useraccountinfo_kiskis'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
