# Generated by Django 5.1.3 on 2025-02-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0012_remove_cityandcountrycode_country_delete_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('min_points', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='useraccountinfo',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
