# Generated by Django 5.1.3 on 2025-02-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0013_ranks_alter_useraccountinfo_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountinfo',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='new_app.ranks', to_field='rank_number'),
        ),
    ]
